services:
  redis:
    image: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
  kotka-api:
    build:
      context: ./
      dockerfile: ./tools/docker/kotka/dev/kotka-api/Dockerfile
    volumes:
      - .:/app
      - shared-volume:/app/node_modules
    ports:
      - 3333:3333
  kotka:
    build:
      context: ./
      dockerfile: ./tools/docker/kotka/dev/kotka/Dockerfile
    volumes:
      - .:/app
      - shared-volume:/app/node_modules
    ports:
      - 4200:4200
    links:
     - kotka-api
volumes:
  shared-volume:
  redis:
