version: '3.8'
services:
  redis:
    image: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
  kotka-api:
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env.e2e
    build:
      context: ./
      dockerfile: ./tools/docker/kotka/dev/kotka-api/Dockerfile
    volumes:
      - .:/app
      - shared-volume:/app/node_modules
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:3333/api/status || exit 1" ]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 7
  kotka-e2e:
    depends_on:
      kotka-api:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./tools/docker/kotka-e2e/Dockerfile
    volumes:
      - .:/app
      - shared-volume:/app/node_modules
    environment:
      - CYPRESS_TEST_EMAIL=${CYPRESS_TEST_EMAIL}
      - CYPRESS_TEST_PASSWORD=${CYPRESS_TEST_PASSWORD}
volumes:
  shared-volume:
  redis:
