version: '3'
services:
  kotka-api:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./tools/docker/dev/kotka-api/Dockerfile
    volumes:
      - .:/app
      - shared-volume:/app/node_modules
    ports:
      - 3333:3333
  kotka:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./tools/docker/dev/kotka/Dockerfile
    volumes:
      - .:/app
      - shared-volume:/app/node_modules
    ports:
      - 4200:4200
    links:
     - kotka-api
volumes:
  shared-volume:
