import { FieldType, PresetSetup } from '@luomus/label-designer';

export const genericLabel: PresetSetup = {
  name: 'GenericLabel',
  setup: {
    page: {
      'height.mm': 297,
      'width.mm': 210,
      'paddingTop.mm': 10,
      'paddingLeft.mm': 10,
      'paddingBottom.mm': 10,
      'paddingRight.mm': 10,
    },
    label: {
      'height.mm': 10,
      'width.mm': 35,
      'marginTop.mm': 0.5,
      'marginLeft.mm': 0.5,
      'marginBottom.mm': 0.5,
      'marginRight.mm': 0.5,
      'font-family': 'Arial',
      'font-size.pt': 5,
    },
    border: 'none',
    labelItems: [
      {
        type: 'field',
        style: { 'width.mm': 10, 'height.mm': 10 },
        x: 0,
        y: 0,
        fields: [
          {
            field: 'uri',
            content: 'http://tun.fi/ID',
            label: 'URI - QRCode',
            type: FieldType.qrCode,
          },
        ],
        _id: 1,
      },
      {
        type: 'field',
        y: 5,
        x: 10.5,
        fields: [
          {
            field: '',
            label: 'Text line 1',
            type: FieldType.text,
            content: 'Text line 1',
            separator: '<br>',
          },
          {
            field: '',
            label: 'Text line 2',
            type: FieldType.text,
            content: 'Text line 2',
            separator: '<br>',
          },
        ],
        style: { 'height.mm': 5, 'width.mm': 24 },
        _id: 3,
      },
      {
        type: 'field',
        y: 0,
        x: 10.5,
        fields: [
          {
            field: 'domain',
            label: 'Domain',
            content: 'http://tun.fi/',
            type: FieldType.domain,
            separator: '<br>',
          },
          {
            field: 'id',
            label: 'ID',
            type: FieldType.id,
            content: 'ID',
            prefix: '&nbsp;&nbsp;&nbsp;&nbsp;',
            _menuOpen: true,
          },
        ],
        style: { 'height.mm': 4.5, 'width.mm': 24 },
        _id: 4,
      },
    ],
    backSideLabelItems: [],
    valueMap: {},
  },
};

export const fungi: PresetSetup = {
  name: 'Fungi',
  setup: {
    page: {
      'height.mm': 297,
      'width.mm': 210,
      'paddingTop.mm': 10,
      'paddingLeft.mm': 10,
      'paddingBottom.mm': 10,
      'paddingRight.mm': 10,
    },
    label: {
      'height.mm': 75,
      'width.mm': 90,
      'marginTop.mm': 1,
      'marginLeft.mm': 1,
      'marginBottom.mm': 1,
      'marginRight.mm': 1,
      'font-family': 'Arial',
      'font-size.pt': 8,
      'line-height': '1.15',
    },
    border: 'thin dashed #999',
    labelItems: [
      {
        type: 'field',
        style: { 'width.mm': 15, 'height.mm': 15 },
        x: 74,
        y: 11,
        fields: [
          {
            field: 'uri',
            content: 'http://tun.fi/ID',
            label: 'URI - QRCode',
            type: FieldType.qrCode,
          },
        ],
        _id: 1,
      },
      {
        type: 'field',
        y: 0,
        x: 0,
        fields: [
          {
            field: 'collectionID',
            label: 'Collection',
            separator: '<br>',
            _menuOpen: true,
          },
          {
            field: 'uri',
            label: 'URI',
            type: FieldType.id,
            prefix: 'Specimen ID ',
            styleAppliesTo: 'content',
            style: { 'font-weight': 'bold' },
            separator: '<br>',
            _menuOpen: true,
          },
          {
            field: 'originalCatalogueNumber',
            label: 'Original catalogue number',
            prefix: 'Original catalogue number: ',
            _menuOpen: true,
            style: {},
            styleAppliesTo: 'all',
          },
        ],
        style: {
          'height.mm': 10,
          'width.mm': 90,
          'text-align': 'left',
        },
        _id: 3,
      },
      {
        type: 'field',
        y: 13,
        x: 0,
        fields: [
          {
            field: 'taxon',
            label: 'Species',
            separator: ' ',
            _menuOpen: true,
            style: { 'font-style': 'italic' },
          },
          {
            field: 'author',
            label: 'Taxon author',
            style: {},
            _menuOpen: true,
          },
        ],
        style: { 'height.mm': 6, 'width.mm': 73, 'font-size.pt': 10 },
        _id: 4,
      },
      {
        type: 'field',
        y: 20.719576,
        x: 0,
        fields: [
          {
            field: 'det',
            label: 'Det.',
            prefix: 'Det. ',
            _menuOpen: true,
            styleAppliesTo: 'prefix',
            style: { 'font-weight': 'bold' },
          },
          { field: 'detDate', label: 'Det date' },
        ],
        style: { 'height.mm': 5, 'width.mm': 73 },
        _id: 5,
      },
      {
        type: 'field',
        y: 27,
        x: 0,
        fields: [
          {
            field: 'country',
            label: 'Country',
            style: { 'font-weight': 'bold' },
            separatorAlways: false,
            separator: ', ',
            _menuOpen: true,
            suffix: '',
          },
          {
            field: 'biologicalProvince',
            label: 'Biogeographical province',
            separator: ', ',
            _menuOpen: true,
            suffix: '',
          },
          {
            field: 'municipality',
            label: 'Municipality',
            separator: ', ',
            _menuOpen: true,
            suffix: '',
            separatorAlways: false,
          },
          {
            field: 'locality',
            label: 'Locality names',
            separatorAlways: false,
          },
          {
            field: 'localityDescription',
            label: 'Locality description',
            separator: '<br>',
            separatorAlways: true,
          },
          {
            field: 'latitude',
            label: 'Lat (N)',
            separator: ', ',
            prefix: 'Lat/Lon. ',
            styleAppliesTo: 'prefix',
            style: { 'font-weight': 'bold' },
          },
          {
            field: 'longitude',
            label: 'Lon (E)',
            separator: ' ',
            _menuOpen: true,
            style: {},
          },
          {
            field: 'system',
            label: 'CoordinateSystem',
            valueMap: {
              'MY.coordinateSystemYkj': 'Uniform grid (YKJ)',
              'MY.coordinateSystemWgs84': 'WGS84 and ETRS89, decimal degrees',
              'MY.coordinateSystemWgs84dms':
                'WGS84 or ETRS89, degrees minutes (seconds)',
              'MY.coordinateSystemKkj':
                'KKJ astekoord. = Finnish KKJ decimal (NOT PREFERRED)',
              'MY.coordinateSystemEtrs-tm35fin': 'ETRS-TM35FIN grid',
              'MY.coordinateSystemDd':
                'Decimal degrees with unknown system (NOT PREFERRED)',
              'MY.coordinateSystemDms':
                'Degrees minutes seconds, with unknown system (NOT PREF.)',
            },
            prefix: '(',
            _menuOpen: true,
            suffix: ')',
            separator: '<br>',
            separatorAlways: true,
          },
          {
            field: 'habitatDescription',
            label: 'Habitat description',
            prefix: 'Hab. ',
            _menuOpen: true,
            style: { 'font-weight': 'bold' },
            styleAppliesTo: 'prefix',
            separator: '<br>',
            separatorAlways: true,
          },
          {
            field: 'leg',
            label: 'Leg',
            isArray: true,
            prefix: 'Leg. ',
            _menuOpen: true,
            style: { 'font-weight': 'bold' },
            styleAppliesTo: 'prefix',
            separator: ', ',
            join: '; ',
          },
          {
            field: 'legID',
            label: 'Collector\'s ID',
            prefix: '(',
            _menuOpen: true,
            suffix: ')',
            separator: '<br>',
            separatorAlways: true,
          },
          {
            field: 'dateBegin',
            label: 'Start date',
            prefix: 'Date ',
            _menuOpen: true,
            style: { 'font-weight': 'bold' },
            styleAppliesTo: 'prefix',
            separatorAlways: false,
            separator: '',
          },
          {
            field: 'dateEnd',
            label: 'End date',
            prefix: '-',
            _menuOpen: true,
            separator: '',
          },
        ],
        style: { 'height.mm': 48, 'width.mm': 90 },
        _id: 6,
      },
    ],
    backSideLabelItems: [],
    valueMap: {
      system: { 'WGS84 and ETRS89, decimal degrees': 'WGS84' },
    },
  },
};

export const insectaDet: PresetSetup = {
  name: 'InsectaDet',
  setup: {
    page: {
      'height.mm': 297,
      'width.mm': 210,
      'paddingTop.mm': 10,
      'paddingLeft.mm': 10,
      'paddingBottom.mm': 10,
      'paddingRight.mm': 10,
    },
    label: {
      'height.mm': 10,
      'width.mm': 35,
      'marginTop.mm': 1,
      'marginLeft.mm': 1,
      'marginBottom.mm': 1,
      'marginRight.mm': 1,
      'font-family': 'Arial',
      'font-size.pt': 4,
    },
    border: 'none',
    labelItems: [
      {
        type: 'field',
        style: { 'width.mm': 10, 'height.mm': 10 },
        x: 0,
        y: 0,
        fields: [
          {
            field: 'uri',
            content: 'http://tun.fi/ID',
            label: 'URI - QRCode',
            type: FieldType.qrCode,
          },
        ],
        _id: 1,
      },
      {
        type: 'field',
        y: 0,
        x: 11,
        fields: [
          {
            field: 'domain',
            label: 'Domain',
            type: FieldType.id,
            separator: '<br>',
          },
          {
            field: 'id',
            label: 'ID',
            type: FieldType.id,
            prefix: '&nbsp;&nbsp;&nbsp;&nbsp;',
          },
        ],
        style: { 'height.mm': 4, 'width.mm': 24 },
        _id: 2,
      },
      {
        type: 'field',
        y: 4,
        x: 11,
        fields: [
          {
            field: 'taxon',
            label: 'Species',
            separator: ' ',
            style: { 'font-style': 'italic' },
            _menuOpen: true,
          },
          {
            field: 'sex',
            label: 'sex',
            valueMap: {
              'MY.sexM': 'M - Male',
              'MY.sexF': 'F - Female',
              'MY.sexW': 'W - Worker',
              'MY.sexU': 'U - Unknown',
              'MY.sexN': 'N - Not applicable',
              'MY.sexX': 'X - Gynandromorph',
              'MY.sexE': 'E - multiple',
              'MY.sexC': 'C - Conflicting',
            },
            separator: '<br>',
            separatorAlways: true,
            _menuOpen: true,
          },
          {
            field: 'author',
            label: 'Taxon author',
            separator: '<br>',
            _menuOpen: true,
            separatorAlways: true,
          },
          {
            field: 'det',
            label: 'Det.',
            separator: ', ',
            _menuOpen: true,
            suffix: '&nbsp;det.',
          },
        ],
        style: { 'height.mm': 6, 'width.mm': 24 },
        _id: 3,
      },
    ],
    backSideLabelItems: [],
    valueMap: { sex: { 'M - Male': '♂', 'F - Female': '♀' } },
  },
};

export const vertebrate: PresetSetup = {
  name: 'Vertebrate',
  setup: {
    page: {
      'height.mm': 297,
      'width.mm': 210,
      'paddingTop.mm': 10,
      'paddingLeft.mm': 10,
      'paddingBottom.mm': 10,
      'paddingRight.mm': 10,
    },
    label: {
      'height.mm': 44,
      'width.mm': 61,
      'marginTop.mm': 1,
      'marginLeft.mm': 1,
      'marginBottom.mm': 1,
      'marginRight.mm': 1,
      'font-family': 'Arial',
      'font-size.pt': 7,
    },
    border: 'thin dashed #999',
    labelItems: [
      {
        type: 'field',
        style: { 'width.mm': 15, 'height.mm': 15 },
        x: 45,
        y: 1,
        fields: [
          {
            field: 'uri',
            content: 'http://tun.fi/ID',
            label: 'URI - QRCode',
            type: FieldType.qrCode,
          },
        ],
        _id: 1,
      },
      {
        type: 'field',
        style: {
          'width.mm': 43,
          'height.mm': 4,
          'font-weight': 'bold',
        },
        x: 1,
        y: 1,
        fields: [
          {
            field: 'uri',
            content: 'http://tun.fi/ID',
            label: 'URI',
            type: FieldType.id,
          },
        ],
        _id: 2,
      },
      {
        type: 'field',
        y: 6,
        x: 1,
        fields: [
          {
            field: 'originalCatalogueNumber',
            label: 'Original catalogue number',
          },
        ],
        style: {
          'height.mm': 4,
          'width.mm': 43,
          'font-weight': 'bold',
        },
        _id: 3,
      },
      {
        type: 'field',
        y: 17,
        x: 1,
        fields: [
          {
            field: 'taxon',
            label: 'Species',
            separator: '<br>',
            _menuOpen: true,
            style: { 'font-weight': 'bold', 'font-size.pt': 8 },
            separatorAlways: false,
          },
          {
            field: 'author',
            label: 'Taxon author',
            separator: '<br>',
            _menuOpen: true,
            separatorAlways: true,
          },
          {
            field: 'sex',
            label: 'sex',
            valueMap: {
              'MY.sexM': 'M - Male',
              'MY.sexF': 'F - Female',
              'MY.sexW': 'W - Worker',
              'MY.sexU': 'U - Unknown',
              'MY.sexN': 'N - Not applicable',
              'MY.sexX': 'X - Gynandromorph',
              'MY.sexE': 'E - multiple',
              'MY.sexC': 'C - Conflicting',
            },
            separator: ' ',
            _menuOpen: true,
          },
          { field: 'age', label: 'Age' },
        ],
        style: { 'height.mm': 10, 'width.mm': 59 },
        _id: 4,
      },
      {
        type: 'field',
        y: 28,
        x: 1,
        fields: [
          { field: 'country', label: 'Country' },
          { field: 'municipality', label: 'Municipality' },
          {
            field: 'locality',
            label: 'Locality names',
            separator: '<br>',
            _menuOpen: true,
            separatorAlways: true,
          },
          {
            field: 'dateBegin',
            label: 'Start date',
            separator: '',
            _menuOpen: true,
          },
          {
            field: 'dateEnd',
            label: 'End date',
            separator: '<br>',
            _menuOpen: true,
            separatorAlways: true,
            prefix: '-',
          },
          {
            field: 'leg',
            label: 'Leg',
            isArray: true,
            separator: '<br>',
            _menuOpen: true,
            suffix: '&nbsp;leg.',
            separatorAlways: true,
          },
          {
            field: 'ring',
            label: 'Ring',
            prefix: 'Ring:&nbsp;',
            _menuOpen: true,
          },
        ],
        style: { 'height.mm': 16, 'width.mm': 59 },
        _id: 5,
      },
    ],
    backSideLabelItems: [],
    valueMap: {
      sex: { '': '', 'M - Male': '♂', 'F - Female': '♀' },
      country: { Finland: ' ', FI: ' ', Suomi: ' ' },
    },
  },
};

export const botanical: PresetSetup = {
  name: 'Botanical',
  setup: {
    page: {
      'height.mm': 297,
      'width.mm': 210,
      'paddingTop.mm': 10,
      'paddingLeft.mm': 10,
      'paddingBottom.mm': 10,
      'paddingRight.mm': 10,
    },
    label: {
      'height.mm': 60,
      'width.mm': 80,
      'marginTop.mm': 2,
      'marginLeft.mm': 2,
      'marginBottom.mm': 2,
      'marginRight.mm': 2,
      'font-family': 'Times New Roman',
      'font-size.pt': 8,
    },
    border: 'thin dashed #999',
    labelItems: [
      {
        type: 'field',
        style: { 'width.mm': 15, 'height.mm': 15 },
        x: 65,
        y: 0,
        fields: [
          {
            field: 'uri',
            content: 'http://tun.fi/ID',
            label: 'URI - QRCode',
            type: FieldType.qrCode,
          },
        ],
        _id: 1,
      },
      {
        type: 'field',
        style: {
          'width.mm': 80,
          'height.mm': 4,
          'text-align': 'left',
        },
        x: 0,
        y: 56,
        fields: [
          {
            field: 'uri',
            content: 'http://tun.fi/ID',
            label: 'URI',
            type: FieldType.id,
            prefix: 'Specimen&nbsp;ID&nbsp;',
            _menuOpen: true,
          },
        ],
        _id: 2,
      },
      {
        type: 'field',
        y: 0,
        x: 0,
        fields: [
          {
            field: '',
            label: 'Text line 1',
            type: FieldType.text,
            separator: '<br>',
            _menuOpen: true,
            style: { 'font-weight': 'bold' },
            content: 'Text line 1',
          },
          {
            field: '',
            label: 'Text line 2',
            type: FieldType.text,
            separator: '<br>',
            _menuOpen: true,
            content: 'Text line 2',
          },
          {
            field: '',
            label: 'Text line 3',
            type: FieldType.text,
            content: 'Text line 3',
          },
        ],
        style: {
          'height.mm': 15,
          'width.mm': 64,
          'text-align': 'center',
        },
        _id: 3,
      },
      {
        type: 'field',
        y: 18,
        x: 0,
        fields: [
          {
            field: 'taxon',
            label: 'Species',
            separator: ' ',
            _menuOpen: true,
            style: { 'font-style': 'italic', 'font-size.pt': 10 },
          },
          { field: 'author', label: 'Taxon author' },
        ],
        style: { 'height.mm': 4, 'width.mm': 80 },
        _id: 4,
      },
      {
        type: 'field',
        y: 25,
        x: 0,
        fields: [
          { field: 'country', label: 'Country', separator: '. ' },
          {
            field: 'biologicalProvince',
            label: 'Biogeographical province',
            separator: '. ',
          },
          {
            field: 'municipality',
            label: 'Municipality',
            separator: '. ',
          },
          {
            field: 'locality',
            label: 'Locality names',
            separator: '. ',
          },
          {
            field: 'localityDescription',
            label: 'Locality description',
            separator: '. ',
          },
          {
            field: 'habitatDescription',
            label: 'Habitat description',
            separator: '<br>',
            separatorAlways: true,
          },
          {
            field: 'system',
            label: 'CoordinateSystem',
            valueMap: {
              'MY.coordinateSystemYkj': 'Uniform grid (YKJ)',
              'MY.coordinateSystemWgs84': 'WGS84 and ETRS89, decimal degrees',
              'MY.coordinateSystemWgs84dms':
                'WGS84 or ETRS89, degrees minutes (seconds)',
              'MY.coordinateSystemKkj':
                'KKJ astekoord. = Finnish KKJ decimal (NOT PREFERRED)',
              'MY.coordinateSystemEtrs-tm35fin': 'ETRS-TM35FIN grid',
              'MY.coordinateSystemDd':
                'Decimal degrees with unknown system (NOT PREFERRED)',
              'MY.coordinateSystemDms':
                'Degrees minutes seconds, with unknown system (NOT PREF.)',
            },
            prefix: 'Coordinates&nbsp;(',
            suffix: ')',
            separator: ' ',
          },
          {
            field: 'latitude',
            label: 'Lat (N)',
            prefix: '',
            suffix: '&nbsp;N',
          },
          { field: 'longitude', label: 'Lon (E)', suffix: '&nbsp;E' },
        ],
        style: {
          'height.mm': 15,
          'width.mm': 79,
          'line-height': '1.5',
        },
        _id: 5,
      },
      {
        type: 'field',
        y: 41,
        x: 0,
        fields: [{ field: 'date_roman', label: 'Date with Roman' }],
        style: { 'height.mm': 4, 'width.mm': 17 },
        _id: 6,
      },
      {
        type: 'field',
        y: 46,
        x: 18,
        fields: [
          {
            field: 'leg',
            label: 'Leg',
            isArray: true,
            separator: '<br>',
            _menuOpen: true,
            separatorAlways: true,
            join: '; ',
            prefix: 'leg.&nbsp;',
          },
          {
            field: 'det',
            label: 'Det.',
            separator: ' ',
            _menuOpen: true,
            prefix: 'det.&nbsp;',
          },
          { field: 'detDate', label: 'Det date' },
        ],
        style: {
          'height.mm': 9,
          'width.mm': 62,
          'text-align': 'right',
        },
        _id: 7,
      },
    ],
    backSideLabelItems: [],
    valueMap: {
      system: {
        'WGS84 and ETRS89, decimal degrees': 'wgs84dd',
        'WGS84 or ETRS89, degrees minutes (seconds)': 'wgs84dms',
        'Uniform grid (YKJ)': 'YKJ',
      },
    },
  },
};
