apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kotka
  name: kotka
spec:
  replicas: 1
  selector:
    io.kompose.service: kotka
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kotka
    spec:
      containers:
        - env:
            - name: LAJI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kotka-secret
                  key: LAJI_API_TOKEN
            - name: LAJI_API_URL
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: LAJI_API_URL
            - name: LAJI_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: LAJI_AUTH_URL
            - name: LAJI_STORE_URL
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: LAJI_STORE_URL
            - name: LAJI_STORE_AUTH
              valueFrom:
                secretKeyRef:
                  name: kotka-secret
                  key: LAJI_STORE_AUTH
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: kotka-secret
                  key: SESSION_SECRET
            - name: SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: SYSTEM_ID
            - name: TRIPLESTORE_URL
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: TRIPLESTORE_URL
            - name: TRIPLSETORE_AUTH
              valueFrom:
                secretKeyRef:
                  name: kotka-secret
                  key: TRIPLESTORE_AUTH
          image: ' '
          name: kotka
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - kotka
        from:
          kind: ImageStreamTag
          name: kotka:latest
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
