apiVersion: apps.openshift.io/v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kotka
  name: kotka
spec:
  ports:
    - name: "4200"
      port: 4200
      targetPort: 4200
  selector:
    io.kompose.service: kotka
status:
  loadBalancer: {}
