kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: kotka-api
  creationTimestamp: null
  namespace: kotka
  labels:
    io.kompose.service: kotka-api
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: kotka-api
      generation: null
      importPolicy: {}
      referencePolicy:
        type: ""
status:
  dockerImageRepository: "image-registry.openshift-image-registry.svc:5000/kotka/kotka-api"