apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kotka-api
  name: kotka-api
spec:
  replicas: 1
  selector:
    io.kompose.service: kotka-api
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kotka-api
    spec:
      containers:
        - env:
            - name: LAJI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kotka-secret
                  key: LAJI_API_TOKEN
            - name: LAJI_API_URL
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: LAJI_API_URL
            - name: LAJI_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: LAJI_AUTH_URL
            - name: LAJI_STORE_URL
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: LAJI_STORE_URL
            - name: LAJI_STORE_AUTH
              valueFrom:
                secretKeyRef:
                  name: kotka-secret
                  key: LAJI_STORE_AUTH
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: kotka-secret
                  key: SESSION_SECRET
            - name: SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: SYSTEM_ID
            - name: TRIPLESTORE_URL
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: TRIPLESTORE_URL
            - name: TRIPLSETORE_AUTH
              valueFrom:
                secretKeyRef:
                  name: kotka-secret
                  key: TRIPLESTORE_AUTH
          image: >-
            image-registry.openshift-image-registry.svc:5000/kotka/kotka-api
          imagePullPolicy: Always
          name: kotka-api
          ports:
            - containerPort: 3333
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - kotka-api
        from:
          kind: ImageStreamTag
          name: kotka-api:latest
      type: ImageChange

