kind: Service
apiVersion: v1
metadata:
  name: kotka
  namespace: kotka
  creationTimestamp: null
  labels:
    io.kompose.service: kotka
spec:
  ports:
    - name: "4200"
      protocol: TCP
      port: 4200
      targetPort: 8080
  selector:
    app: kotka
    io.kompose.service: kotka
    tier: frontend
status:
  loadBalancer: {}