kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: kotka-api
  creationTimestamp: null
  namespace: kotka
  labels:
    io.kompose.service: kotka-api
spec:
  strategy:
    type: Recreate
    resources: {}
  replicas: 1
  revisionHistoryLimit: 0
  test: false
  selector:
    app: kotka
    io.kompose.service: kotka-api
    tier: backend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kotka
        io.kompose.service: kotka-api
        tier: backend
    spec:
      containers:
        - name: kotka-api
          image: "image-registry.openshift-image-registry.svc:5000/kotka/kotka-api"
          ports:
            - containerPort: 3333
              protocol: TCP
          env:
            - name: LAJI_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kotka-secret
                  key: LAJI_API_TOKEN
            - name: LAJI_API_URL
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: LAJI_API_URL
            - name: LAJI_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: LAJI_AUTH_URL
            - name: LAJI_STORE_URL
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: LAJI_STORE_URL
            - name: LAJI_STORE_AUTH
              valueFrom:
                secretKeyRef:
                  name: kotka-secret
                  key: LAJI_STORE_AUTH
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: kotka-secret
                  key: SESSION_SECRET
            - name: SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: SYSTEM_ID
            - name: TRIPLESTORE_URL
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: TRIPLESTORE_URL
            - name: TRIPLESTORE_AUTH
              valueFrom:
                secretKeyRef:
                  name: kotka-secret
                  key: TRIPLESTORE_AUTH
            - name: TRIPLESTORE_AUTH
              valueFrom:
                secretKeyRef:
                  name: kotka-secret
                  key: TRIPLESTORE_AUTH
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: database-password
            - name: SECURE_COOKIE
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: SECURE_COOKIE
            - name: OLD_KOTKA_URL
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: OLD_KOTKA_URL
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
