kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: kotka
  creationTimestamp: null
  labels:
    io.kompose.service: kotka
spec:
  strategy:
    type: Recreate
    resources: {}
  replicas: 1
  revisionHistoryLimit: 0
  test: false
  selector:
    app: kotka
    io.kompose.service: kotka
    tier: frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kotka
        io.kompose.service: kotka
        tier: frontend
    spec:
      containers:
        - name: kotka
          image: "image-registry.openshift-image-registry.svc:5000/kotka/kotka"
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SYSTEM_ID
              valueFrom:
                configMapKeyRef:
                  name: kotka-config
                  key: SYSTEM_ID
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always